const dummyData = {listing:
   { city: 'San Francisco',
     collection_ids: null,
     country: 'United States',
     has_double_blind_reviews: false,
     id: 2736358,
     instant_book_enabled: false,
     instant_bookable: false,
     lat: 37.767464651512164,
     lng: -122.44482720597567,
     medium_url: 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=medium',
     name: 'Garden Retreat steps from Haight St',
     native_currency: 'USD',
     picture_url: 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=large',
     preview_encoded_png: 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//AcfFwf8AAAUFBQ0MC/379gHLx6zz+QX9+vkVFBD18fEBh3xoMDU74dzZ7d/RAQsQNX8X+svbJkQAAAAASUVORK5CYII=',
     price: 185,
     price_formatted: '$185',
     price_native: 185,
     scrim_color: '#443120',
     smart_location: 'San Francisco, CA',
     thumbnail_url: 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=small',
     user: { user: [Object] },
     user_id: 8638224,
     x_medium_picture_url: 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=x_medium',
     xl_picture_url: 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=x_large',
     address: 'San Francisco, CA, United States',
     bathrooms: 1,
     bedrooms: 1,
     beds: 2,
     cancellation_policy: 'flexible',
     check_in_time: 14,
     check_in_time_end: 'NOT_SELECTED',
     check_in_time_ends_at: null,
     check_in_time_start: '14',
     check_out_time: 12,
     country_code: 'US',
     has_availability: true,
     hosts: [ [Object] ],
     listing_native_currency: 'USD',
     market: 'San Francisco',
     max_nights: 1125,
     min_nights: 2,
     neighborhood: 'Haight-Ashbury',
     person_capacity: 3,
     picture_count: 12,
     picture_urls:
      [ 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37512889/fd5e74b1_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513019/c40cd857_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513066/ca98721a_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513150/22e0207f_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513108/beb7fca3_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513201/597dec37_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513251/81e78831_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513233/c0e5864d_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513344/03b1f068_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37513428/1f7e684b_original.jpg?aki_policy=large',
        'https://a0.muscache.com/im/pictures/37877641/20059d32_original.jpg?aki_policy=large' ],
     preview_encoded_pngs:
      [ 'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//AcfFwf8AAAUFBQ0MC/379gHLx6zz+QX9+vkVFBD18fEBh3xoMDU74dzZ7d/RAQsQNX8X+svbJkQAAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAOUlEQVQIHWPcNqdZSN2GnYuXhZmB6f9vxs0tQWyaTv/Y+DgYf3JwSzIuzbfn1HH+yy5w/cQ+dWtfAEtQDpSPCyvrAAAAAElFTkSuQmCC',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//Ad/d1vTy9PX2+v38+QoLCgHb1b/s6Ovw9PYC7NsIFiUBmY148OTUDgX/Bfv3HThTHR0dcT1RHxMAAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//AdTU0gAA/fv5+/7/APDq5gHa2M7j4NwMDRPo5uYI/fABhn100dPVNigVEAb/CAD646AbldrGvnYAAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//AcrLyaqqqDAvMA4ZIRUB7gHIyMXR0dIMCAQIDxceEwcBq6ahys3RJiMgw7u0MTg83L0TGohgo9EAAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//Ac/Q0fn4+Pf4+BsbFwMBAQHP0NT18e7v9/ofGAjg3d8Bhnx9CQsOEBUQ19LQ4tvUpogaeGTbyIAAAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAECAIAAADJUWIXAAAAS0lEQVQIHQFAAL//AdnW0e3k2ggTHgMCAwECBAHCsqEBAwUHFB4IBwf9/QABuayd8/X7EBoeDg0L/gADAWBAKwUB+UFlfx4aFBIWHcHeE7OFCguVAAAAAElFTkSuQmCC',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAECAIAAADJUWIXAAAAS0lEQVQIHQFAAL//AdXTz/Hz9gwMC/76+QUHBgHc2tTp8voIBAPx6eQZHBsB7+/qzNrjDAT9APHjCQ4ZAc3LweLn7hsS/9bLyAUNGHbHIilGL8zTAAAAAElFTkSuQmCC',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//AcLBvRISEPv7/QkKDf//AAG7urnw7PIUFxAjJiX29fgBpaOd3NjTHB4fEDA/+AQQPlUWYZKdKN4AAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAOUlEQVQIHWOc2ur95P1bTs5/woICZmZRjD3Njut3XuPl4lJV5nN1kmQsL1f+9opVWopfVIzr2fsXAKn8EQT/rcaTAAAAAElFTkSuQmCC',
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAADCAIAAADUVFKvAAAAO0lEQVQIHQEwAM//AamXfQUEBBcgLdbV1fv67QGhk30jJCYCBAjZ1dCyuLMBrJqAAgEDFRkd+/r34uDf6pQV/1P2N/QAAAAASUVORK5CYII=',
        'iVBORw0KGgoAAAANSUhEUgAAAAQAAAAFCAIAAADtz9qMAAAATElEQVQIHQFBAL7/AXZ5fP4CB+Lo6fr4+wGnqq/T1NTo5uH3+f0BjY6R4+Xm/Pr2y8bIAaWoqM/P0svMxfby8wFxcWvj4uPm5uQlIyS2Qix7UAldjAAAAABJRU5ErkJggg==' ],
     primary_host:
      { about: 'I\'m a recent transplant to San Francisco from nearby Tiburon.  I love walking my dog in the parks nearby and cycling the Bay area. I work  with a contemporary ballet company and try to take advantage of the wealth of music, art galleries, and restaurants here. My home is a classic Edwardian built in 1904 yet my taste is modern and comfortable - can\'t wait to share it with you.',
        first_name: 'Sara',
        has_completed_ib_salmon_flow_v2: false,
        has_dismissed_ib_salmon_flow: true,
        has_dismissed_ib_salmon_flow_v2: false,
        has_profile_pic: true,
        ib_salmon_flow_data: [],
        id: 8638224,
        identity_verified: false,
        is_active_rtb_host: true,
        is_superhost: true,
        languages: [],
        picture_url: 'https://a0.muscache.com/im/users/8638224/profile_pic/1378336598/original.jpg?aki_policy=profile_x_medium',
        reviewee_count: 212,
        thumbnail_url: 'https://a0.muscache.com/im/users/8638224/profile_pic/1378336598/original.jpg?aki_policy=profile_small' },
     property_type: 'House',
     reviews_count: 211,
     room_type: 'Entire home/apt',
     room_type_category: 'entire_home',
     scrim_colors:
      [ '#443120',
        '#473527',
        '#483726',
        '#42382F',
        '#191410',
        '#2C1D18',
        '#412B1C',
        '#624C3D',
        '#473728',
        '#27250C',
        '#362E1A',
        '#1D1D1B' ],
     special_offer: null,
     state: 'CA',
     thumbnail_urls:
      [ 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37512889/fd5e74b1_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513019/c40cd857_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513066/ca98721a_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513150/22e0207f_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513108/beb7fca3_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513201/597dec37_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513251/81e78831_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513233/c0e5864d_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513344/03b1f068_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37513428/1f7e684b_original.jpg?aki_policy=small',
        'https://a0.muscache.com/im/pictures/37877641/20059d32_original.jpg?aki_policy=small' ],
     xl_picture_urls:
      [ 'https://a0.muscache.com/im/pictures/37512945/0b81f8d8_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37512889/fd5e74b1_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513019/c40cd857_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513066/ca98721a_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513150/22e0207f_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513108/beb7fca3_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513201/597dec37_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513251/81e78831_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513233/c0e5864d_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513344/03b1f068_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37513428/1f7e684b_original.jpg?aki_policy=x_large',
        'https://a0.muscache.com/im/pictures/37877641/20059d32_original.jpg?aki_policy=x_large' ],
     zipcode: '94117',
     bed_type: 'Real Bed',
     bed_type_category: 'real_bed',
     currency_symbol_left: '$',
     force_mobile_legal_modal: true,
     require_guest_profile_picture: false,
     access: 'Your own entrance means you can come and go as you wish and enter the apartment through new french doors from the garden. There is a mini fridge, Nespresso coffee maker, toaster oven and goodies awaiting you in the breakfast bar area. Free wifi, cable, and maps of the area as well. Laundry is  available upon request conveniently located just outside the door inside the apartment.',
     amenities:
      [ 'TV',
        'Cable TV',
        'Wifi',
        'Pets live on this property',
        'Indoor fireplace',
        'Heating',
        'Family/kid friendly',
        'Washer',
        'Dryer',
        'Smoke detector',
        'Carbon monoxide detector',
        'Essentials',
        'Hangers',
        'Hair dryer',
        'Iron',
        'Laptop friendly workspace',
        'Private living room',
        'Private entrance',
        'Bathtub',
        'Hot water',
        'Coffee maker',
        'Refrigerator',
        'Dishes and silverware',
        'Oven',
        'Garden or backyard',
        'Hot water kettle' ],
     amenities_ids:
      [ 1,
        2,
        4,
        17,
        27,
        30,
        31,
        33,
        34,
        35,
        36,
        40,
        44,
        45,
        46,
        47,
        56,
        57,
        61,
        77,
        90,
        91,
        93,
        95,
        101,
        137 ],
     calendar_updated_at: 'yesterday',
     cancel_policy: 3,
     cancel_policy_short_str: 'Flexible',
     cleaning_fee_native: 75,
     currency_symbol_right: null,
     description: 'One bedroom sanctuary with a beautiful garden view and cozy fireplace. Comes with it\'s own entrance just steps from bus lines, train and all that Haight Street has to offer. Complete privacy with a separate bedroom, bathroom, and  breakfast bar.\n\nIf you want to be within walking distance to Golden Gate Park, Haight St, Buena Vista Park, and Cole Valley, this is the spot. Full size bed in the bedroom with 400 thread count sheets and a pull-out twin in the living room. Just installed fireplace and large screen tv makes hanging out fun in the comfortable  living room. Bathroom has a shower within the tub and white fluffy towels.\n\nYour own entrance means you can come and go as you wish and enter the apartment through new french doors from the garden. There is a mini fridge, Nespresso coffee maker, toaster oven and goodies awaiting you in the breakfast bar area. Free wifi, cable, and maps of the area as well. Laundry is  available upon request conveniently located just outside the door inside the apartment.\n\nI live upstairs and will meet you upon arrival then be available as much as you need or not.  I\'ve been exploring the neighborhood and take long walks with my dog so there\'s not much I haven\'t seen!\n\nYou will hear from many that this is the  best neighborhood in SF. I chose this area for the many  Victorian homes, the ease of mass transit, the walkability, and the abundance of parks,restaurants, and nightlife nearby.\nAs a recent transplant to this area I can tell you that the stores, coffee shops, restaurants, and pubs are great here. I forget I have a car most of the time! Street parking is easy except for Wednesday 8-10 due to street cleaning.\n\nEverything is a walk away or jump on the many bus lines that are at the corner. In minutes you can be at the Ferry Building, Marina, Presidio, Castro, UCSF Medical building, Market Street and Union Square. The N-Judah line also stops in nearby Cole Valley. I walk most places - post office, grocery store, pharmacy, bank, hardware, and clothing stores. The Magnolia Brew Pub is a block away with all their own draft beers. The number of walking distance hang-outs is amazing - Zam Zam is a fun martini bar, Sparrow is my new favorite farm to table restaurant and Club Deluxe offers pizza and live music every night! Plus Golden Gate Park is a walk away which means you can walk to all the museums and gardens there. I have books, maps and all the info you\'ll need to navigate your trip here.\n\nI live upstairs and will be available for any questions - my friendly Australian Shepherd, Boo,  may come downstairs to say hello in the backyard.\nI have  registered with the city of San Francisco and my license is #STR- (Phone number hidden by Airbnb)',
     description_locale: 'en',
     experiences_offered: 'none',
     extra_user_info: null,
     extras_price_native: 75,
     guests_included: 2,
     has_agreed_to_legal_terms: true,
     has_license: true,
     has_viewed_cleaning: null,
     has_viewed_ib_perf_dashboard_panel: true,
     has_viewed_terms: true,
     house_rules: 'I\'m OK with pets and the unit opens up to the backyard which makes it easy but my dog is out there so your pet must get along!',
     instant_book_welcome_message: '',
     instant_booking_allowed_category: 'off',
     interaction: 'I live upstairs and will meet you upon arrival then be available as much as you need or not.  I\'ve been exploring the neighborhood and take long walks with my dog so there\'s not much I haven\'t seen!',
     is_location_exact: true,
     jurisdiction_names: [ 'SAN FRANCISCO' ],
     jurisdiction_rollout_names: [ 'SAN FRANCISCO' ],
     language: 'en',
     license: 'STR-0000380',
     listing_cleaning_fee_native: 75,
     listing_monthly_price_native: 3750,
     listing_price_for_extra_person_native: 50,
     listing_security_deposit_native: 250,
     listing_weekend_price_native: null,
     listing_weekly_price_native: 1200,
     locale: 'en',
     localized_check_in_time_window: 'Anytime after 2PM',
     localized_check_out_time: '12PM (noon)',
     localized_city: 'San Francisco',
     map_image_url: 'https://maps.googleapis.com/maps/api/staticmap?maptype=roadmap&markers=37.767464651512164%2C-122.44482720597567&size=480x320&zoom=15&client=gme-airbnbinc&channel=monorail-prod&signature=SP2kHz9v6PTG7a2LbZ8C3ubWaZE%3D',
     max_nights_input_value: null,
     min_nights_input_value: 2,
     monthly_price_factor: 0.75,
     monthly_price_native: 3750,
     neighborhood_overview: 'You will hear from many that this is the  best neighborhood in SF. I chose this area for the many  Victorian homes, the ease of mass transit, the walkability, and the abundance of parks,restaurants, and nightlife nearby.\nAs a recent transplant to this area I can tell you that the stores, coffee shops, restaurants, and pubs are great here. I forget I have a car most of the time! Street parking is easy except for Wednesday 8-10 due to street cleaning.',
     notes: 'I live upstairs and will be available for any questions - my friendly Australian Shepherd, Boo,  may come downstairs to say hello in the backyard.\nI have  registered with the city of San Francisco and my license is #STR- (Phone number hidden by Airbnb)',
     photos:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ],
     picture_captions:
      [ 'Enter through french doors to a light filled living room ',
        'Looking through the room to the garden entrance',
        'The oak armoire is full of games and San Francisco travel books',
        'The breakfast bar with a Nespresso machine and hot water kettle and tea. Plus a full desk to spread out and work on.',
        'A cozy fireplace with a flat screen tv',
        'This couch pulls out to a twin bed',
        'New towels, tub with a shower ',
        'This double bed has a feather-top mattress cover - so it\'s comfy!',
        'Big closet, chest of drawers, and reading lights ',
        'Green and tranquil backyard',
        'Your own separate entrance to the left of the garage',
        'Street view - It\'s a gracious Edwardian' ],
     price_for_extra_person_native: 50,
     property_type_id: 2,
     public_address: 'San Francisco, CA, United States',
     require_guest_phone_verification: false,
     requires_license: true,
     security_deposit_formatted: '$250',
     security_deposit_native: 250,
     security_price_native: 250,
     space: 'If you want to be within walking distance to Golden Gate Park, Haight St, Buena Vista Park, and Cole Valley, this is the spot. Full size bed in the bedroom with 400 thread count sheets and a pull-out twin in the living room. Just installed fireplace and large screen tv makes hanging out fun in the comfortable  living room. Bathroom has a shower within the tub and white fluffy towels.',
     square_feet: null,
     star_rating: 5,
     summary: 'One bedroom sanctuary with a beautiful garden view and cozy fireplace. Comes with it\'s own entrance just steps from bus lines, train and all that Haight Street has to offer. Complete privacy with a separate bedroom, bathroom, and  breakfast bar.',
     time_zone_name: 'America/Los_Angeles',
     transit: 'Everything is a walk away or jump on the many bus lines that are at the corner. In minutes you can be at the Ferry Building, Marina, Presidio, Castro, UCSF Medical building, Market Street and Union Square. The N-Judah line also stops in nearby Cole Valley. I walk most places - post office, grocery store, pharmacy, bank, hardware, and clothing stores. The Magnolia Brew Pub is a block away with all their own draft beers. The number of walking distance hang-outs is amazing - Zam Zam is a fun martini bar, Sparrow is my new favorite farm to table restaurant and Club Deluxe offers pizza and live music every night! Plus Golden Gate Park is a walk away which means you can walk to all the museums and gardens there. I have books, maps and all the info you\'ll need to navigate your trip here.',
     weekly_price_factor: 0.95,
     weekly_price_native: 1200,
     incentives: [],
     additional_house_rules: 'I\'m OK with pets and the unit opens up to the backyard which makes it easy but my dog is out there so your pet must get along!',
     in_building: false,
     in_toto_area: false,
     recent_review: { review: [Object] },
     toto_opt_in: null,
     commercial_host_info: null,
     review_rating_accuracy: 10,
     review_rating_checkin: 10,
     review_rating_cleanliness: 9,
     review_rating_communication: 10,
     review_rating_location: 10,
     review_rating_value: 9,
     is_business_travel_ready: false,
     wireless_info: null },
  metadata: {} };

  export default dummyData;